datacenters:
 - dc1
type: system
region: 
count: 1

job_name: fabiolb

# Driver will allow you to specify how we are running FabioLB. It can be 
# "docker", "exec", or "raw_exec".
driver: raw_exec

# Configuration used when Docker is set as Driver:
docker:
  image: fabiolb/fabio
  tag: "1.5.14-go1.15"
  network_mode: nohost

exec:
  # To get the right version and the go Version, have a look at the GitHub
  # release page: https://github.com/fabiolb/fabio/releases/latest
  version: "1.5.14"
  fullVersion: "1.5.14-go1.15"

services:
  # Proxy is enabled by default
  proxy:
    # Set port to an empty/falsy value to have it randomly selected by Nomad
    port: 9999
  ui:
    enable: true
    port: 9998

# Update strategy can be "rolling", "canary", "blue_green"
# read more: https://learn.hashicorp.com/tutorials/nomad/job-update-strategies
# and Nomad docs: https://www.nomadproject.io/docs/job-specification/update 
update: 
  enable: true
  strategy: rolling
  max_parallel: 1
  health_check: 
  min_healthy_time: "15s"
  healthy_deadline: "1m"
